// Mocks generated by Mockito 5.0.16 from annotations
// in testing_in_flutter/test/get_album_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:testing_in_flutter/web_service.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeResponse_0<T> extends _i1.Fake implements _i2.Response<T> {}

/// A class which mocks [WebService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebService extends _i1.Mock implements _i3.WebService {
  MockWebService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<dynamic>> getFirstAlbum() => (super.noSuchMethod(
          Invocation.method(#getFirstAlbum, []),
          returnValue:
              Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>()))
      as _i4.Future<_i2.Response<dynamic>>);
  @override
  String toString() => super.toString();
}
